language: node_js

node_js:
  - 8
  - 10
  - 12
  - stable

sudo: false

script:
  - yarn test

after_success:
  - yarn report
  - yarn docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  fqdn: emitting.sova.dev
  on:
    branch: master
    node_js: "stable"

branches:
  except:
    - gh-pages
